version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
         # cypress-command: npx cypress run --browser chrome
          cypress-command: 'npx cypress run --parallel --record'
          start-command: 'npm run start'
          parallelism: 4 # use 4 CircleCI machines to finish quickly
         # install-browsers: true
         # start-command: npm run start:dev


