version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome 
          install-browsers: true
          start-command: 'npm run cy-record:run'
         - store_test_results:
         path: cypress\video
build:
  working_directory: /D:\cy-test\NewCypressAutomation\cypress
  steps:
    - run:
        name: Creating  Artifacts
        command: |
          echo "my artifact file" > /tmp/art-1;
          mkdir /tmp/artifacts;
          echo "my artifact files in a dir" > /tmp/artifacts/art-2;

    - store_artifacts:
        path: /tmp/art-1
        destination: artifact-file

    - store_artifacts:
        path: /tmp/artifacts

